version: '1.0'

services:

  #nginx:
  #  build:
  #    context: ./.nginx
  #  volumes:
  #    - .:/var/www/appvue
  #  ports:
  #    - 8080:80
  #  networks:
  #    - vueapp

  app:
    container_name: jonykarol_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Cambiar el puerto 8085 por 80 en produccion
      - '${VITE_APP_PORT}:81'
    #x-develop:
    #  watch:
    #    - path: ./src/
    #      target: /app/src/
    #      action: sync


  certbot:
    image: certbot/certbot
    volumes:
      - ../certificado_ssl/etc-letsencrypt:/etc/letsencrypt
      - ../certificado_ssl/var-lib-letsencrypt:/var/lib/letsencrypt
      - ../certificado_ssl/var-log-letsencrypt:/var/log/letsencrypt